routes/web.php
<?php


Route::get('/', function () {
    return view('app.login');
})->middleware('guest:admin')->name('home');
Route::namespace('Open')->group(function(){
	Route::get('register','CustomerRegisterController@register')->name('customer.register')->middleware('guest:admin');
	Route::post('register','CustomerRegisterController@create')->name('customer.create');
	Route::post('login','AdminsLoginController@login')->name('login');
	Route::get('/logout','AdminsLoginController@logout')->name('logout');
});
// ->middleware('auth:admin')
Route::namespace('Backend')->prefix('admin')->name('admin.')->middleware('auth:admin')->group(function(){

	Route::get('/','DashboardController@index')->name('dashboard');
	Route::post('/dashboard_customer_details','DashboardController@dashboard_customer_details')->name('dashboard_customer_details');
	Route::post('/dashboard_customer_delete','DashboardController@dashboard_customer_delete')->name('dashboard_customer_delete');
	Route::post('/dashboard_customer_destroy','DashboardController@dashboard_customer_destroy')->name('dashboard_customer_destroy');
	Route::post('/dashboard_customer_disable','DashboardController@dashboard_customer_disable')->name('dashboard_customer_disable');
	Route::post('/dashboard_customer_disabled','DashboardController@dashboard_customer_disabled')->name('dashboard_customer_disabled');
	
	



});

// Auth::routes();

app/Admin.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Admin extends Authenticatable
{
    use Notifiable;

    protected $table = 'admins';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'remember_token',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Customer.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Customer extends Authenticatable {

    use Notifiable;
    
    protected $table = 'customers';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password' ,'remember_token', 'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /* define status */

    public function status(){
        return [
            0 => 'Deactive',
            1 => 'Active',


        ];
    }


}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Admin extends Authenticatable
{
    use Notifiable;

    protected $table = 'admins';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'remember_token',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Backend/DashboardController.php
<?php
namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Customer;

class DashboardController extends Controller {    

    /** main dashboard **/
    public function index() {
        $result = Customer::orderBy('id','desc')->paginate(5); 
        return view('app.dashboard', compact('result'));
    }

    /** customer details **/

    public function dashboard_customer_details(Request $request){
        $model = Customer::findOrFail($request->id);
        return view('app.dashboard_customer_details', compact('model'));
    }
    /** customer delete modal **/

    public function dashboard_customer_delete(Request $request){
        $model = Customer::findOrFail($request->id);
        return view('app.dashboard_customer_delete', compact('model'));
    }

    /** customer destroy **/

    public function dashboard_customer_destroy(Request $request){
        Customer::destroy($request->id);
        return response()->json(['success' => true]);
    }
    /** customer disable **/

    public function dashboard_customer_disable(Request $request){
        $model = Customer::findOrFail($request->id);
        return view('app.dashboard_customer_disable', compact('model'));
    }
    
    /** customer disabled **/

    public function dashboard_customer_disabled(Request $request){
        $model = Customer::findOrFail($request->id);
        if($model->status == 1){
            $model->update(['status' => 0]);
        }else{
            $model->update(['status' => 1]);            
        }
        return response()->json(['success' => true]);
    }
    


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller {

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index() {
        return view('home');
    }

    public function customer() {
        return view('home');
    }

}

app/Http/Controllers/Open/AdminsLoginController.php
<?php

namespace App\Http\Controllers\Open;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class AdminsLoginController extends Controller
{

    public function login(Request $request){
        $validated = $this->validate($request, [
            'email' => ['required', 'string', 'email',],
            'password' => ['required', 'string', 'min:6',],
        ]);
        if($validated){
    	   return $this->loggin_check($request) ? redirect()->route('admin.dashboard') : redirect()->back()->with('msg','Invalid email or password');
        }
        // dd($request->all());
    }

    public function loggin_check($request){
    	$data = $request->only('email','password');
        $remember = $request->remember ? true : false;
    	$login_attempt = Auth::guard('admin')->attempt($data,$remember);
    	return $login_attempt ? true : false; 

    }
    public function logout(Request $request){
    	Auth::guard('admin')->logout();
        return redirect('/');
    }
}

app/Http/Controllers/Open/CustomerRegisterController.php
<?php
namespace App\Http\Controllers\Open;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Customer;

class CustomerRegisterController extends Controller
{
    public function register(){
    	return view('app.register');
    }

    public function create(Request $request)
    {
    	$data = $request->except('_token','_method');
	    $validated = $this->validate($request, [
	        'name' => ['required', 'string', 'max:300'],
	        'email' => ['required', 'string', 'email', 'max:100', 'unique:customers'],
	        'password' => ['required', 'string', 'min:6', 'confirmed'],
        ]);
        if($validated){
	        $created = Customer::create([
	            'name' => $request['name'],
	            'email' => $request['email'],
	            'password' => bcrypt($request['password']),
	        ]);
	        if($created){
	        	return redirect()->back()->with('msg', true);
	        }	
        }
    }


}

resources/views/app/dashboard.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header"><h2>{{ 'Admin Dashboard' }}</h2></div>
                <div class="card-body">
                    <div class="alert alert-success">
                      <h3 class="text-center">Our valuable customers</h3>
                    </div>
                    @isset($result)
                    <table class="table table-striped table-sm table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th width="5%">ID</th>
                                <th width="25%">Name</th>
                                <th width="25%">Email</th>
                                <th width="10%" class="text-center">Status</th>
                                <th width="35%" class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($result as $model)
                            <tr>
                                <td>{{ $model->id }}</td>
                                <td>{{ $model->name }}</td>
                                <td>{{ $model->email }}</td>
                                <td class="text-center">
                                    @if($model->status != 0)
                                    <span class="badge badge-success">{{ $model->status()[$model->status] }}</span>
                                    @else
                                    <span class="badge badge-secondary">{{ $model->status()[$model->status] }}</span>
                                    @endif
                                </td>
                                <td class="text-center">
                                    <button type="button" class="btn btn-success btn-sm btn_view" data-id="{{$model->id}}">View</button>
                                    {{-- <button type="button" class="btn btn-primary btn-sm btn_edit" data-id="{{$model->id}}">Edit</button> --}}
                                    <button type="button" class="btn btn-danger btn-sm btn_delete" data-id="{{$model->id}}">Delete</button>
                                    <button type="button" class="btn btn-warning btn-sm btn_disable" data-id="{{$model->id}}">
                                        @if($model->status == 0)
                                        Active
                                        @else
                                        Deactive
                                        @endif

                                    </button>
                                </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                    </table>
                    {{ $result->links() }}
                    @else
                    Nothing found
                    @endisset
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    $(document).ready(function(){

        /* disable ajax request */

        {

            $('.btn_disable').click(function(e){
                const ID = $(this).data('id');
                const data_object = {
                  URL : "{{ route('admin.dashboard_customer_disable') }}",
                  DATA : { id: ID},
                  DATATYPE : "",
                  METHOD : 'post',
                };
                custom_ajax_call(data_object);                

            });   
        }

        /* End: disable ajax request */

        /* disabled ajax request */

        {

        $('body').on('click','.btn_disabled',function(e){
            const ID = $(this).data('id');
            const data_object = {
              URL : "{{ route('admin.dashboard_customer_disabled') }}",
              DATA : { id: ID},
              DATATYPE : "json",
              NOMODAL : true,
              METHOD : 'post',
              RELOAD : true,
            };
            custom_ajax_call(data_object);              

          });   
        }
        /* End: disabled ajax request */

        /* view ajax request */
        {

            $('.btn_view').click(function(e){
                let id = $(this).data('id');
                const URL = "{{ route('admin.dashboard_customer_details') }}";
                const DATA = { id: id};
                const DATATYPE = "html";
                const METHOD = "post";
                custom_ajax_call({URL,DATA,DATATYPE,METHOD});                

            });   
        }

        /* End: view ajax request */

        /* delete ajax request */

        {

            $('.btn_delete').click(function(e){
                let id = $(this).data('id');
                const URL = "{{ route('admin.dashboard_customer_delete') }}";
                const DATA = { id: id};
                const DATATYPE = "html";
                const METHOD = "post";
                custom_ajax_call({URL,DATA,DATATYPE,METHOD});                

            });   
        }

        /* End: delete ajax request */

        /* destroy ajax request */

        {

        $('body').on('click','.btn_destroy',function(e){
            const ID = $(this).data('id');
            const data_object = {
              URL : "{{ route('admin.dashboard_customer_destroy') }}",
              DATA : { id: ID},
              DATATYPE : "json",
              NOMODAL : true,
              METHOD : 'post',
              RELOAD : true,
            };
            custom_ajax_call(data_object);              

          });   
        }
        /* End: destroy ajax request */


    });
</script>
@endpush

resources/views/app/dashboard_customer_delete.blade.php
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <!-- Modal Header -->
      <div class="modal-header  text-center">
        <h4 class="modal-title">Customer Details</h4>
        <button type="button" class="close" data-dismiss="modal">×</button>
      </div>
      <form method="POST" action="">
        @csrf
        @method('post')
        <!-- Modal body -->
        <div class="modal-body">
          <p><strong>Name: </strong> {{ $model->name }}</p>
          <p><strong>Email: </strong> {{ $model->email }}</p>
          <p><strong>Status: </strong>
            @if($model->status != 0)
            <span class="badge badge-success">{{ $model->status()[$model->status] }}</span>
            @else
            <span class="badge badge-secondary">{{ $model->status()[$model->status] }}</span>
            @endif
          </p>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer text-center">
          <h4>Do you want to delete?
          <button type="button" class="btn btn-danger btn_destroy" data-id="{{ $model->id }}">Yes</button>
          <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
          </h4>
        </div>
      </form>
      
    </div>
  </div>
</div>

resources/views/app/dashboard_customer_details.blade.php
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <!-- Modal Header -->
      <div class="modal-header  text-center">
        <h4 class="modal-title">Customer Details</h4>
        <button type="button" class="close" data-dismiss="modal">×</button>
      </div>
      
      <!-- Modal body -->
      <div class="modal-body">
        <p><strong>Name: </strong> {{ $model->name }}</p>
        <p><strong>Email: </strong> {{ $model->email }}</p>
        <p><strong>Status: </strong> 
          @if($model->status != 0)
          <span class="badge badge-success">{{ $model->status()[$model->status] }}</span>
          @else
          <span class="badge badge-secondary">{{ $model->status()[$model->status] }}</span>
          @endif
        </p>
      </div>
      
      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
      
    </div>
  </div>
</div>

</div>

resources/views/app/dashboard_customer_disable.blade.php
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <!-- Modal Header -->
      <div class="modal-header  text-center">
        <h4 class="modal-title">Customer Details</h4>
        <button type="button" class="close" data-dismiss="modal">×</button>
      </div>
      <form method="POST" action="">
        @csrf
        @method('post')
        <!-- Modal body -->
        <div class="modal-body">
          <p><strong>Name: </strong> {{ $model->name }}</p>
          <p><strong>Email: </strong> {{ $model->email }}</p>
          <p><strong>Status: </strong>
            @if($model->status != 0)
            <span class="badge badge-success">{{ $model->status()[$model->status] }}</span>
            @else
            <span class="badge badge-secondary">{{ $model->status()[$model->status] }}</span>
            @endif
          </p>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer text-center">
          <h4>Are you sure?
          <button type="button" class="btn btn-danger btn_disabled" data-id="{{ $model->id }}">Yes</button>
          <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
          </h4>
        </div>
      </form>
      
    </div>
  </div>
</div>

resources/views/app/login.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                @if(session()->has('msg'))
                    
                    <div class="alert alert-danger alert-dismissible">
                      <button type="button" class="close" data-dismiss="alert">&times;</button>
                      <strong>Error!</strong> {{ session()->get('msg') }}
                    </div>
                @endif
                <div class="card-header">Login</div>

                <div class="card-body">
                     
                        <form method="POST" action="{{ route('login') }}">
                            @csrf
                            @method('post')

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">E-Mail Address</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" autocomplete="email" autofocus>

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password">

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>

                                               <label class="form-check-label" for="remember">
                                            Remember Me
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Login
                                    </button>

                                </div>
                            </div>
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/register.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                @if(session()->has('msg'))
                    
                    <div class="alert alert-success alert-dismissible">
                      <button type="button" class="close" data-dismiss="alert">&times;</button>
                      <strong>Success!</strong> Customer created successfully
                    </div>
                @endif
                <div class="card-header">Register</div>



                <div class="card-body">
                    <form method="post" action="{{ route('customer.create') }}">
                        @csrf
                        @method('post')

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/_app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name', 'Laravel') }}</title>
        <!-- Scripts -->
        
        
        <script src="{{ asset('js/app.js') }}"></script>
        <script type="text/javascript">
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        </script>
        <!-- Re-Capcha Script -->
        <script src='https://www.google.com/recaptcha/api.js'></script>
        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body>
        <div id="app">
            <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
                <div class="container">
                    @guest
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ env('APP_NAME', 'Laravel') }}
                    </a>
                    @else
                    <a class="navbar-brand" href="{{ route('admin.dashboard') }}">
                        {{ env('APP_NAME', 'Laravel') }}
                    </a>
                    @endguest
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">
                        </ul>
                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('customer.register') }}">{{ __('Register') }}</a>
                            </li>
                            @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>
            <main class="py-4">
                @yield('content')
            </main>
        </div>
        <!-- Push scripts dynamically -->
        
        <script>            

            /* Custom ajax call function */
            function custom_ajax_call({URL,DATA,DATATYPE,METHOD,NOMODAL,RELOAD}){
                $.ajax({
                    url: URL,
                    data: DATA,
                    dataType: DATATYPE,
                    type : METHOD,
                    success: function(result,status,xhr){
                        if(NOMODAL){
                            $('.modal').modal('hide');
                        }else{
                            $('body').append(result);
                            $('.modal').modal('show');
                        }
                        if(RELOAD){
                            location.reload();
                        }


                    },
                    error: function(xhr){
                        alert("An error occured: " + xhr.status + " " + xhr.statusText);
                    }
                });
            }
            /* End: Custom ajax call function */
            
            $(document).ready(function(){
                /* Hide all modal after modal hidden event */
                $('body').on('hidden.bs.modal',function(){
                    $('.modal').remove();
                });
                /* End: Hide all modal after modal hidden event */

            });
        </script>
        @stack('scripts')
    </body>
</html>